title: Victor Guillard - Data Scientist & AI Enthusiast # Titre plus percutant

logo: "/images/new-photo-1.jpg?raw=true" # Assurez-vous d'avoir une photo professionnelle "profile.jpg" dans /images/

description: > 
  Data Scientist, titulaire d’un Master 2 M2MO (Université Paris Cité, Centrale Paris & ENSAE). <br><br>
  Projets avancés en IA (mesure de l’incertitude dans les réseaux de neurones) et expérience terrain : développement web (Go), cloud computing, DevOps et architecture système. <br><br>
  Enseignant en mathématiques, j’ai renforcé ma pédagogie et ma capacité à vulgariser des concepts techniques pour des publics variés. Je recherche un environnement collaboratif et exigeant où je pourrai perfectionner mes acquis et contribuer à des projets ambitieux. <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0 # Thème minimaliste et professionnel, parfait pour un portfolio

plugins:
  - jekyll-remote-theme # Plugin nécessaire pour remote_theme

google_analytics: UA-000000-0 
