title: Victor Guillard

logo: "/images/new-photo-3.jpg?raw=true"

description: > 
  Data Scientist, titulaire d’un Master 2 M2MO (Université Paris Cité, Centrale Paris & ENSAE). <br><br>
  Projets avancés en IA (mesure de l’incertitude dans les réseaux de neurones) et expérience terrain : développement web (Go), cloud computing, DevOps et architecture système. <br><br>
  Enseignant en mathématiques, j’ai renforcé ma pédagogie et ma capacité à vulgariser des concepts techniques pour des publics variés. Je recherche un environnement collaboratif et exigeant où je pourrai perfectionner mes acquis et contribuer à des projets ambitieux. <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

google_analytics: UA-000000-0 
